version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: yarn install
      - run: yarn build-libraries
      - run: yarn add file:./dist/whistler/iam
      - run: yarn add file:./dist/whistler/cognito
      - run: yarn build:prod
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist/console-app
  deploy:
    working_directory: ~/project
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/project
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Sync to S3
          command: aws s3 sync --delete ~/project/dist/console-app s3://${S3_BUCKET}
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - staging
                - develop
