version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - checkout
      - run: yarn install
      - run: yarn build:prod
      - run: yarn lint-ci
      - run: yarn test-ci
      - persist_to_workspace:
          root: ~/project
          paths:
            - apps/ros-fe/dist
  deploy:
    working_directory: ~/project
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: ~/project
      - aws-cli/install
      - aws-cli/configure
      - run:
          name: Sync to S3
          command: aws s3 sync --delete ~/project/apps/ros-fe/dist s3://${S3_BUCKET}
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
